name: built_redux
version: 7.3.5
description:
  A state management library written in dart that enforces immutability
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.29.0 <0.32.0'
  build: '>=0.10.0 <0.13.0'
  built_collection: '>=1.0.0 <4.0.0'
  built_value: ^5.2.0
  source_gen: '>=0.7.0 <0.8.0'

dev_dependencies:
  build_runner: ^0.7.10+1
  built_value_generator: ^5.2.0
  dart_dev: ^2.0.0-alpha
  dart_style: '>=0.2.4 <2.0.0'
  coverage: '>=0.9.0 <0.11.0'
  test: '>=0.12.0 <0.14.0'

environment:
  sdk: ">=1.13.7 <2.0.0"

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
